version: "3"

services:
  web:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lost-but-found
    ports:
      - "8000:8000"
      - "2525:2525"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "lost-but-found-volume:/var/lib/postgresql/data"
volumes:
  lost-but-found-volume:
